# Generated by Django 4.1.7 on 2023-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('Za', 'Zambian'), ('MA', 'Malawian'), ('So', 'South African'), ('Zi', 'Zimbabwean'), ('Co', 'Congolis'), ('In', 'Indian'), ('Ch', 'Chinese'), ('Mo', 'Moroccan'), ('Bo', 'Botswanan'), ('Ni', 'Nigerian')], default='Za', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
