# Generated by Django 4.1.7 on 2023-05-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('Ka', 'Kalingalinga'), ('Ti', 'Tiyende Pamodzi'), ('So', 'Soweto'), ('Ka', 'Kafue'), ('Oc', 'October'), ('Za', 'Zambezi'), ('In', 'International'), ('Pr', 'President'), ('Kw', 'Kwacha'), ('Af', 'Africa'), ('VE', 'VET'), ('Le', 'Levy Mwanawasa')], default='Ka', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('Na', 'Natural Sciences'), ('Ag', 'Agricultural Sciences'), ('Mi', 'Mines'), ('Ed', 'Education'), ('Hu', 'Humaninities and Social Sciences'), ('En', 'Engineering'), ('Ve', 'Vetnery Medicine'), ('Co', 'Confucius Studies'), ('La', 'Law')], default='Na', max_length=2),
        ),
    ]
