# Generated by Django 4.1.7 on 2023-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('Kalingalinga', 'Kalingalinga'), ('Tiyende Pamodzi', 'Tiyende Pamodzi'), ('Soweto', 'Soweto'), ('Kafue', 'Kafue'), ('October', 'October'), ('Zambezi', 'Zambezi'), ('International', 'International'), ('President', 'President'), ('Kwacha', 'Kwacha'), ('Africa', 'Africa'), ('VET', 'VET'), ('Levy Mwanawas', 'Levy Mwanawasa')], default='Ka', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('Zambian', 'Zambian'), ('Malawian', 'Malawian'), ('South African', 'South African'), ('Zimbabwean', 'Zimbabwean'), ('Congolis', 'Congolis'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Moroccan', 'Moroccan'), ('Botswanan', 'Botswanan'), ('Nigerian', 'Nigerian')], default='Za', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('Natural Sciences', 'Natural Sciences'), ('Agricultural Sciences', 'Agricultural Sciences'), ('Mines', 'Mines'), ('Education', 'Education'), ('Humaninities and Social Sciences', 'Humaninities and Social Sciences'), ('Engineering', 'Engineering'), ('Vetnery Medicine', 'Vetnery Medicine'), ('Confucius Studies', 'Confucius Studies'), ('Law', 'Law')], default='Na', max_length=50),
        ),
    ]
