# Generated by Django 4.1.7 on 2023-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
