# Generated by Django 4.1.7 on 2023-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(default='unread', max_length=10),
        ),
    ]
